modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = ""
[[mods]]
modId = "structurewarden"
version = "0.0.1"
displayName = "Structure Warden ID"
displayURL = ""
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
A mod that allows the creation of specific conditions that limits what a player may/may not do until said conditions are met.
'''
[[dependencies.structurewarden]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
